language: node_js
env:
  - CXX=g++-5

node_js:
  - "8"

sudo: required
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

install:
  - npm install

script:
  - npm run testrpc &
  - npm run test